# Generated by Django 6.0 on 2025-12-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_ticket', models.CharField(max_length=20, unique=True, verbose_name='Ticket de Jira')),
                ('description', models.TextField(verbose_name='Descripción del Requerimiento')),
                ('is_qa_approved', models.BooleanField(default=False, verbose_name='Aprobado por QA')),
                ('date_completed', models.DateField(auto_now_add=True)),
                ('unit_tests_total', models.PositiveIntegerField(default=0)),
                ('unit_tests_passed', models.PositiveIntegerField(default=0)),
                ('unit_tests_failed', models.PositiveIntegerField(default=0)),
                ('functional_cases', models.PositiveIntegerField(default=0)),
                ('functional_bugs', models.PositiveIntegerField(default=0)),
                ('integration_cases', models.PositiveIntegerField(default=0)),
                ('integration_bugs', models.PositiveIntegerField(default=0)),
                ('regression_cases', models.PositiveIntegerField(default=0)),
                ('regression_bugs', models.PositiveIntegerField(default=0)),
                ('production_bugs', models.PositiveIntegerField(default=0, verbose_name='Bugs escapados a Prod')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='metrics.developer')),
            ],
        ),
    ]
