# Generated by Django 6.0 on 2025-12-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='end_date_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Real'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='estimated_effort_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Esfuerzo Estimado (Hrs)'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='start_date_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Real'),
        ),
    ]
