# Generated by Django 6.0 on 2025-12-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_requirement_end_date_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='rol',
            field=models.CharField(choices=[('DBA', 'DBA'), ('DBA_Becario', 'DBA_Becario'), ('DEV_Junior', 'DEV_Junior'), ('DEV_Senior', 'DEV_Senior'), ('QA_Junior', 'QA_Junior'), ('QA_Senior', 'QA_Senior')], default='DEV_Junior', max_length=20, verbose_name='Rol'),
        ),
    ]
