# Generated by Django 6.0 on 2025-12-16 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_developer_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Desarrollador', 'verbose_name_plural': 'Desarrolladores'},
        ),
        migrations.AddField(
            model_name='requirement',
            name='rejection_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cant. Rechazos QA'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='rol',
            field=models.CharField(choices=[('DBA', 'Administrador de Base de Datos'), ('DBA_Becario', 'Becario DBA'), ('DEV_Junior', 'Desarrollador Junior'), ('DEV_Senior', 'Desarrollador Senior'), ('QA_Junior', 'QA Junior'), ('QA_Senior', 'QA Senior')], default='DEV_Junior', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='date_completed',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='metrics.developer', verbose_name='Desarrollador Asignado'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='estimated_effort_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Esfuerzo Estimado (Hrs)'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='functional_bugs',
            field=models.PositiveIntegerField(default=0, verbose_name='Bugs Funcionales'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='functional_cases',
            field=models.PositiveIntegerField(default=0, verbose_name='Casos Funcionales'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='integration_bugs',
            field=models.PositiveIntegerField(default=0, verbose_name='Bugs Integración'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='integration_cases',
            field=models.PositiveIntegerField(default=0, verbose_name='Casos Integración'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='is_qa_approved',
            field=models.BooleanField(default=False, verbose_name='¿Aprobado por QA?'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='production_bugs',
            field=models.PositiveIntegerField(default=0, verbose_name='Bugs en Producción'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='regression_bugs',
            field=models.PositiveIntegerField(default=0, verbose_name='Bugs Regresión'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='regression_cases',
            field=models.PositiveIntegerField(default=0, verbose_name='Casos Regresión'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='unit_tests_failed',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Unitarias Fallidas'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='unit_tests_passed',
            field=models.PositiveIntegerField(default=0, verbose_name='Unitarias Pasadas'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='unit_tests_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Unitarias'),
        ),
    ]
