# Generated by Django 6.0.1 on 2026-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_alter_developer_options_requirement_rejection_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='jira_ticket',
            field=models.CharField(max_length=250, unique=True, verbose_name='Ticket de Jira'),
        ),
    ]
